### PR TITLE
add workaround rule for LP: #1584456

### PR DESCRIPTION
**Pull request by jdstrand**

### CODE REVIEW

**Comment by tyhicks** [comment]
Looks correct to me.

**Comment by jdstrand** [comment]
"2016/08/12 16:32:31 Cannot allocate linode:ubuntu-16.04-64-grub: authentication failed" is the testsuite failure which is unrelated to the PR.

**Comment by zyga** [comment]
+1, thank you for fixing this

**Comment by fallen** [comment]
Thanks!

**Pull request merged**
