### PR TITLE
chdir() to '/' before setting up private /tmp (LP: #1592402)

### PR DESCRIPTION
**Pull request by jdstrand**
chdir() to '/' before setting up private /tmp so private /tmp works when user is in /tmp (LP: #1592402)

### CODE REVIEW

**Comment by mvo5** [comment]
:+1: Would be nice to mention in the comment that this is an issue if the user is in /tmp (that is my understanding at least)

**Comment by zyga** [comment]
This looks good. Thank you Jamie.

One word of notice: we're trying to unify error messages around `cannot ...` rather than `unable to`. I will merge it and update the tree to reflect that.

**Comment by zyga** [comment]
I'll merge this manually in a sec.

**Comment by zyga** [comment]
Thanks for that and for de-conflicting. Merging now

**Pull request merged**
