### PR TITLE
allow snap-confine to mount on /dev/pts/ptmx for LXD with /dev/ptmx symlink

### PR DESCRIPTION
**Pull request by jdstrand**

### CODE REVIEW

**Comment by jdstrand** [comment]
FYI, this was uploaded to yakkety in 1.0.42-0ubuntu3. If preparing a new upload, please don't drop this patch.

**Comment by jdstrand** [comment]
The test failure has nothing to do with this PR:

```
2016/09/28 22:36:58 Cannot allocate linode:ubuntu-16.04-64-grub: authentication failed
```

**Comment by zyga** [comment]
The patch looks good, is there a bug number tracking this?

**Comment by jdstrand** [comment]
@zyga there is no bug.

**Comment by jdstrand** [comment]
Actually, LP: #1628616 would fit.

**Pull request merged**
